= SpringBean子类替换实现逻辑扩展
:lang: zh_CN
:toc:
:toclevels: 5
:sectnums:
:sectnumlevels: 5

== 背景
项目二开扩展逻辑不可避免,Aop实现的扩展相比子类重写方法扩展, 有以下几个缺点:

. AOP扩展需要改为xThis调用,往往要改源码,已是代码入侵行为; 另外xThis是自身注入自己,易引起循环依赖;
. 相对继承实现,AOP扩展性能损失更大;
. 如果源码扩展更改了方法名, AOP扩展逻辑不易被发现错误;
. AOP扩展比较灵活,导致扩展代码可能分布多处,扩展不易管理,也不便查找定位;
. AOP扩展逻辑需要考虑入参,出参,方法名编写.而继承方式是重写方法,使用IDE工具直接override method就可以自动生成;
. AOP扩展难理解,调用顺序也不直观;而子类重写方法内前后或中间调用父类的多个方法都非常方便,也容易得到返回值,逻辑简单易懂;

另外子类重写方法扩展同样要求public或protected实例方法.AOP实现也有此限制.综上原因,实现子类替换BeanStarter是个不错方案.实现结果：不依赖公司现有组件,与AOP扩展不冲突.如果认同此扩展方式,项目可逐步替换为此方式,老项目也可以使用.

== 使用
=== 引入starter依赖
[source,xml]
----
<dependency>
    <groupId>io.github.xiejx618</groupId>
    <artifactId>replace-bean-boot-starter</artifactId>
    <version>${replace-bean.version}</version>
</dependency>
----

=== 继承父类编写扩展逻辑
[source,java]
----
@Replace
public class HelloServiceExt extends HelloService {

    public void sayHello() {
        System.out.println("sub hello world!");
        test();
    }

    private void test() {
        System.out.println("sub HelloService.test");
    }
}
----
如果是自动扫描,就是指定扫描包+使用@Replace, 其中@Replace可以指定替换beanName,不指定时则使用父类名推断,排序用于一个bean被多次扩展时,选择一个更小值的类;也可以在replace.replaceBeanMap配置,key指定替换beanName,value指定替换bean的全限定名或者后面追加英文冒号和排序值;

=== 配置

[source,yaml]
----
replace:
  enabled: true
  packages: io.github.xiejx618.demo.ext
  replaceBeanMap:
    helloService: io.github.xiejx618.demo.ext.HelloServiceExt
----
packages和replaceBeanMap必须要配置一个,也可以两个都配.

. enabled:是否开启bean替换功能.默认值为true;
. packages:扫描替换Bean包名:可为空, 多个包时使用英文逗号分割; 查找的类可以是当前包或多层子包;
. replaceBeanMap:枚举为指定替换bean的map结构.key是要替换的beanName,value是被使用替换的bean的全限定名或者后面追加英文冒号和排序值,如:io.github.xiejx618.demo.ext.HelloServiceExt:100;


=== 最佳实践
. 源码开发逻辑应将可能要扩展的实例成员(包括字段与方法)定义为protected或public,供子类使用.
. 扩展代码应统一放到一个包下面, 方便代码管理. 应尽详细指定具体包,缩小扫描范围,加快扫描速度;
. 配置方式建议使用replace.packages指定替换类查找,当不满足时,再考虑使用replaceBeanMap. @Replace可以不指定BeanName和排序值时,建议不指定.

== 需求分析
第三,四部分内容为原理性(可选看).需求有几个点:1.获取当前Bean必须替换后的Bean;2.如果某个Bean依赖之前的Bean,那之前的Bean也必须改为替换后的Bean;3.无论单例或多例Bean,都能够替换生效;4.一个Bean可以被多次替换;5.通过组件方便配置使用;

针对某个bean的生命周期主要如下:
----
阶段1：Bean元信息配置阶段
阶段2：Bean元信息解析阶段
阶段3：将Bean注册到容器中
阶段4：BeanDefinition合并阶段
阶段5：Bean Class加载阶段
阶段6：Bean实例化阶段
  Bean实例化前阶段
  Bean实例化阶段
阶段7：合并后的BeanDefinition处理
阶段8：属性赋值阶段
  Bean实例化后阶段
  Bean属性赋值前阶段
  Bean属性赋值阶段
阶段9：Bean初始化阶段
  Bean Aware接口回调阶段
  Bean初始化前阶段
  Bean初始化阶段
  Bean初始化后阶段
阶段10：所有单例bean初始化完成后阶段
阶段11：Bean的使用阶段
阶段12：Bean销毁前阶段
阶段13：Bean销毁阶段
----
应用上下文主要过程如下：
----
// 1.刷新上下文环境
prepareRefresh();
// 2.初始化 beanFactory，对配置文件进行解读
ConfigurableListableBeanFactory beanFactory = obtainFreshBeanFactory();
// 3.对 beanFactory 进行功能扩展
prepareBeanFactory(beanFactory);
// 4.专门留给子类作扩展用，这是一个空的方法
postProcessBeanFactory(beanFactory);
// 5.注册并执行 BeanFactoryPostProcessor 后置处理器
invokeBeanFactoryPostProcessors(beanFactory);
// 6.注册 BeanPostProcessor 后置处理器，在 getBean() 创建 bean 时调用
registerBeanPostProcessors(beanFactory);
// 7.初始化 Message 源，即不同语言消息体，国际化处理
initMessageSource();
// 8.注册多播器，事件监听器的管理者
initApplicationEventMulticaster();
// 9.专门留给子类初始化其它 bean 用，这是一个空的方法
onRefresh();
// 10.注册监听器
registerListeners();
// 11.初始化剩余的 bean (部分在 invokeBeanFactoryPostProcessors 已经初始化)
finishBeanFactoryInitialization(beanFactory);
// 12.完成刷新，通知生命周期处理器 LifecycleProcessor 刷新过程，同时发布 ContextRefreshedEvent 通知别人
finishRefresh();
----
. 单例Bean实例初始化一次,多次获取都为同一个对象; 多例Bean,多次获取会多次实例初始化;
. Bean的生命周期并不是对齐上面过程, 因此并不能简单只看上下文运行过程.
. Bean的注册可能在上面过程的beanFactory准备好后的任意某个点，bean的初始化(getBean)也有可能出现在上面过程的某个点.
. 焦点在于Bean的生命周期实例化之前阶段(上面的阶段6),上面的阶段1-3不在getBean内.
. 所以,范围缩小在阶段4-6找切入点(回调或勾子).针对已有的切入点,最终找出InstantiationAwareBeanPostProcessor的postProcessBeforeInstantiation阶段修改逻辑比较适合. 毫无疑问,使用Spring Boot Starter实现插件比较合适;

== 实现细节(问题考虑)
1.核心是修改Bean的注册定义的BeanClass,后续就直接使用替换后BeanClass实现化. 另外,InstantiationAwareBeanPostProcessor的postProcessBeforeInstantiation返回实例化对象也是一种思路. 只是选择了修改Bean定义更靠前,经验上觉得更可靠.
----
public Object postProcessBeforeInstantiation(Class<?> beanClass, String beanName) throws BeansException {
    if (replaceBeanMap.containsKey(beanName)) {
        BeanDefinition mergedBeanDefinition = beanFactory.getMergedBeanDefinition(beanName);//如果bean不存在时,会抛异常
        mergedBeanDefinition.setBeanClassName(replaceBeanMap.get(beanName).getBeanClass());
    }
    return InstantiationAwareBeanPostProcessor.super.postProcessBeforeInstantiation(beanClass, beanName);
}
----

2.bean实例化用的是MergedBeanDefinition,所以使用beanFactory.getMergedBeanDefinition,而不是beanFactory.getBeanDefinition

3.考虑应将bean替换信息尽早注册到ReplaceBeanBeanPostProcessor#replaceBeanMap.所以定义 ReplaceBeanBeanPostProcessor也是一个BeanFactoryPostProcessor.在它实例化的时候,加载bean替换信息. 在它实例化的时候,由于无法使用ConfigurationPropertiesBindingPostProcessor绑定,所以使用Binder.get(environment).bind主动绑定一下,并且定义为PriorityOrdered是期望它更早注册到beanFactory的beanPostProcessor列表中. 如果想替换PriOrdered BeanPostProcessor bean,因为ReplaceBeanBeanPostProcessor还未注册到beanFactory则无法适用, 但能正常适用定义了Ordered或非Ordered BeanPostProcessor Bean替换.

4.如果一个bean被多个子类继承,或多层次继承.每次注册时,如果已注册了某个bean的替换则会比较排序,只有当前排序值比现值还小,才会替换.